server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://logs-prod-020.grafana.net/loki/api/v1/push
    basic_auth:
      username: ${LOKI_USERNAME}
      password: ${LOKI_API_KEY}

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'instance'
      - source_labels: ['__meta_docker_container_label_job']
        target_label: 'job'
        action: replace
      - source_labels: ['__meta_docker_container_label_environment']
        target_label: 'environment'
        action: replace
      - source_labels: ['__meta_docker_container_label_level']
        target_label: 'level'
        action: replace
      - source_labels: ['__meta_docker_container_name']
        regex: 'family-tree-3_(.*)_1'
        target_label: 'service'
        replacement: '$1'
