name: CD Deploy Notification Service

on:
  workflow_dispatch:

jobs:
  deploy-notification-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy Notification Service to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          docker compose -f docker-compose.prod.yml pull notification-service
          docker compose -f docker-compose.prod.yml up -d --no-deps notification-service
          echo "Notification Service deployment completed successfully!"
