name: CD Deploy Graphviz PDF Converter

on:
  workflow_dispatch:

jobs:
  deploy-graphviz-pdf-converter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy Graphviz PDF Converter to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          docker compose -f docker-compose.prod.yml pull graphviz-pdf-converter
          docker compose -f docker-compose.prod.yml up -d --no-deps graphviz-pdf-converter
          echo "Graphviz PDF Converter deployment completed successfully!"
